allowBuilds:
  '@sentry/cli': true
  '@clerk/shared': true
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  cypress: true
  esbuild: true
  msw: true
  playwright: true
  protobufjs: true
  puppeteer: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
  workerd: true
overrides:
  lodash@<4.17.24: ">=4.17.24"
  axios@<1.15.0: ">=1.15.0"
  tmp@<0.2.4: ">=0.2.4"
  @tootallnate/once@<3.0.1: ">=3.0.1"
  uuid@<14.0.0: ">=14.0.0"
  esbuild@<0.25.0: ">=0.25.0"
